### PR TITLE
Fixed Saleforce

### PR DESCRIPTION
**Pull request by supergibbs**
I was trying to use the `AspNet.WebHooks.ConnectedService` to setup Salesforce but was very confused. I eventually figured it out using [this post](http://blogs.msdn.com/b/webdev/archive/2015/09/07/integrating-with-salesforce-using-asp-net-webhooks-preview.aspx). The pull request adds some template variables and corrects the generated handler for Salesforce. Some of the other receivers might want to use this too but I haven't gone through them all.

### CODE REVIEW

**Comment by bradygaster** [comment]
@supergibbs have you tested this change with the other, non-salesforce WebHooks and verified it doesn't break anything in those guys? I presume so from looking at the code but just want you to sign off that it's not breaking any of the other providers. 

And massive thanks for the interest and the PR! Awesome to have some contributions to the tooling!

**Comment by bradygaster** [comment]
@supergibbs have you tested this change with the other, non-salesforce WebHooks and verified it doesn't break anything in those guys? I presume so from looking at the code but just want you to sign off that it's not breaking any of the other providers. 

And massive thanks for the interest and the PR! Awesome to have some contributions to the tooling!

**Comment by supergibbs** [comment]
I haven't needed the other ones so I haven't tested them myself but the PR shouldn't affect any other Webhooks unless the `WebHooksConnectedServiceConfig.json` is updated for them.

**Comment by bradygaster** [comment]
That's what I thought from looking at the commit. I'll accept it as it truly looks like the other would be unaffected. I'll test myself too, and if I see anything odd arise I'll undo the PR and revert. Should be okay tho - thanks again for the contribution.

**Pull request merged**
